subprojects: Upgrade Catch2 from v2.11.1 to v3.3.2
The upgrade means that we no longer need to compile our own catch2_main
library since the wrap file now provides its own.

This fixes the build failures we're seeing with GCC 13:

    In file included from /usr/include/signal.h:328,
                     from ../subprojects/Catch2-2.11.1/single_include/catch2/catch.hpp:7955,
                     from ../catch2_main.cpp:2:../subprojects/Catch2-2.11.1/single_include/catch2/catch.hpp:10735:58: error: call to non-'constexpr' function 'long int sysconf(int)'
    10735 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
          |                                                          ^~~~~~~~~~~